import { actionTypeHelper } from './actionTypeHelper';

export const USER_PREFERENCE = actionTypeHelper('USER_PREFERENCE', {
  INIT_USER_PREFERENCE: '',
  UPDATE_CREATE_ACCOUNT_FORM: '',
  ASYNC_POST_INITIALIZE_FORM: '',
  ASYNC_CHANGE_DEFAULT_REPOSITORY: '',
  ASYNC_VERIFICATION_ACCESS_TOKEN: '',
  ASYNC_ADD_ACCOUNT: '',
  CANCEL_CREATE_ACCOUNT: '',
  START_CREATE_ACCOUNT: '',
  ASYNC_DELETE_ACCOUNT: '',
  ASYNC_UPDATE_CURRENT_ACCOUNT_INDEX: '',
  ASYNC_SET_SHOW_LINE_NUMBER: '配置编辑器是否显示行号',
  ASYNC_SET_EDITOR_LIVE_RENDERING: '配置编辑器是否实时渲染',
  ASYNC_SET_SHOW_QUICK_RESPONSE_CODE: '',
  ASYNC_HIDE_TOOL: '隐藏插件',
  ASYNC_REMOVE_TOOL: '移除插件'
});

export const USER_INFO = actionTypeHelper('USER_INFO', {
  ASYNC_FETCH_USER_INFO: ''
});

export const CLIPPER = actionTypeHelper('CLIPPER', {
  ASYNC_FETCH_REPOSITORY: '获取知识库列表',
  ASYNC_CREATE_REPOSITORY: '创建知识库',
  ASYNC_CREATE_DOCUMENT: '创建问的',
  ASYNC_UPLOAD_IMAGE: '上传图片',
  SELECT_REPOSITORY: '选择知识库',
  UPDATE_TITLE: '',
  START_CREATE_REPOSITORY: '',
  CANCEL_CREATE_REPOSITORY: '',
  CHANGE_CREATE_REPOSITORY_TITLE: '',
  INIT_TAB_INFO: '',
  UPDATE_TEXT_CLIPPER_DATA: '',
  ASYNC_RUN_PLUGIN: '',
  ASYNC_CHANGE_ACCOUNT: ''
});
