export enum ActionMessageType {
  DO_YOU_ALIVE_NOW = 'DO_YOU_ALIVE_NOW',
  ICON_CLICK = 'ICON_CLICK',
  GO_TO_SETTINGS = 'GO_TO_SETTINGS',
  GET_FULL_PAGE_MARKDOWN = 'GET_FULL_PAGE_MARKDOWN',
  GET_READABILITY_MARKDOWN = 'GET_READABILITY_MARKDOWN',
  GET_DOCUMENT_INFO = 'GET_DOCUMENT_INFO',
  GET_SELECT_ITEM = 'GET_SELECT_ITEM',
  CLEAN_SELECT_ITEM = 'CLEAN_SELECT_ITEM',
  GET_SELECT_AREA = 'GET_SELECT_AREA'
}
